version: '2'
services:
  rap_redis:
    container_name: rap_redis
    build: 
      context: .
      dockerfile: redis-dockerfile
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - rap-network
    
  rap_mysql:
    container_name: rap_mysql
    build:
      context: .
      dockerfile: mysql-dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=1qazzaq1"
      - "MYSQL_DATABASE=rap_db"
      - "MYSQL_ROOT_HOST=%"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - rap-network
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=20M',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_bin',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]            
  rap_web:
    container_name: rap_web
    build:
      context: .
      dockerfile: rapweb-dockerfile
    ports:
      - "9000:8080"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
    expose:
      - "8080"
    networks:
      - rap-network
    depends_on:
      - rap_mysql
      - rap_redis
networks:
  rap-network:
    driver: bridge
